package com.myspace.jbpmnt;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CUSTOMER_ID_GENERATOR")
	@javax.persistence.SequenceGenerator(sequenceName = "CUSTOMER_ID_SEQ", name = "CUSTOMER_ID_GENERATOR")
	private java.lang.Long id;
	private java.lang.String name;
	private java.lang.Float coins;

	private java.time.LocalDate registrationDate;

	public Customer() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Float getCoins() {
		return this.coins;
	}

	public void setCoins(java.lang.Float coins) {
		this.coins = coins;
	}

	public java.time.LocalDate getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(java.time.LocalDate registrationDate) {
		this.registrationDate = registrationDate;
	}

	public Customer(java.lang.Long id, java.lang.String name,
			java.lang.Float coins, java.time.LocalDate registrationDate) {
		this.id = id;
		this.name = name;
		this.coins = coins;
		this.registrationDate = registrationDate;
	}

}