package com.myspace.jbpmnt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Customer() {
    }




}