package com.myspace.jbpmnt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "place")
	private java.lang.String place;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "owner")
	private java.lang.String owner;

	@org.kie.api.definition.type.Label(value = "date")
	private java.time.LocalDateTime date;

	@org.kie.api.definition.type.Label(value = "fee")
	private float fee;

	public Event() {
	}

	public java.lang.String getPlace() {
		return this.place;
	}

	public void setPlace(java.lang.String place) {
		this.place = place;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getOwner() {
		return this.owner;
	}

	public void setOwner(java.lang.String owner) {
		this.owner = owner;
	}

	public java.time.LocalDateTime getDate() {
		return this.date;
	}

	public void setDate(java.time.LocalDateTime date) {
		this.date = date;
	}

	public float getFee() {
		return this.fee;
	}

	public void setFee(float fee) {
		this.fee = fee;
	}

	public Event(java.lang.String place, java.lang.Long id,
			java.lang.String owner, java.time.LocalDateTime date, float fee) {
		this.place = place;
		this.id = id;
		this.owner = owner;
		this.date = date;
		this.fee = fee;
	}

}