package com.myspace.jbpmnt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Event() {
    }




}